# https://hands-on-tech.github.io/2018/11/01/kafka-spark-flink-example.html
version: '3.6'

networks:
  bridge:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      bridge:
        aliases:
          - zookeeper
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: test:1:1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      bridge:
        aliases:
          - kafka

  kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile.kafka-client
    tty: true
    depends_on:
      - kafka
    environment:
      TOPIC: "test"
    volumes:
      - ./scala-producer:/scala/producer
    networks:
      - bridge

  kafka-consumer:
    build:
      context: .
      dockerfile: Dockerfile.kafka-client
    tty: true
    depends_on:
      - kafka-producer
    environment:
      TOPIC: "test"
    volumes:
      - ./scala-consumer:/scala/consumer
    networks:
      - bridge

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    environment:
      ZK_HOSTS: "zookeeper:32181"
    ports:
      - 9000:9000
    networks:
      - bridge
